module.exports = {
  apps: [
    {
      name: 'systrack-api',
      script: 'bun',
      args: 'run server/index.ts',
      cwd: './',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env_file: '.env',
      error_file: './logs/pm2-api-error.log',
      out_file: './logs/pm2-api-out.log',
      log_file: './logs/pm2-api-combined.log',
      time: true,
    },
    {
      name: 'systrack-worker',
      script: 'bun',
      args: 'run server/worker/index.ts',
      cwd: './',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env_file: '.env',
      error_file: './logs/pm2-worker-error.log',
      out_file: './logs/pm2-worker-out.log',
      log_file: './logs/pm2-worker-combined.log',
      time: true,
    },
    {
      name: 'systrack-scheduler',
      script: 'bun',
      args: 'run server/scheduler/index.ts',
      cwd: './',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      env_file: '.env',
      error_file: './logs/pm2-scheduler-error.log',
      out_file: './logs/pm2-scheduler-out.log',
      log_file: './logs/pm2-scheduler-combined.log',
      time: true,
    },
    {
      name: 'systrack-whatsapp',
      script: 'bun',
      args: 'run server/whatsapp/index.ts',
      cwd: './',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      env_file: '.env',
      error_file: './logs/pm2-whatsapp-error.log',
      out_file: './logs/pm2-whatsapp-out.log',
      log_file: './logs/pm2-whatsapp-combined.log',
      time: true,
    },
  ],
};
